
server:
  port: 8888

spring:
  application:
    name: auth-server
  security:
    oauth2:
      authorizationserver:
        issuer-url: http://localhost:8888
        introspection-endpoint: /oauth2/token-info

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka